version: 0.2
phases:
  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      - mvn dependency:resolve
  build:
    commands:
      - echo "Building the project..."
      - mvn clean package
artifacts:
  files:
    - target/*.jar